### ISSUE TITLE
Jenkins replaces jobs with same appid and jobid

### ISSUE THREAD

**Issue by bamachrn** [CentOS/container-pipeline-service#103]
When there is entry of multiple tags with same appid and jobid, jenking job builder is replacing the entries with its last entry. As a result no job is getting triggered for the earlier entries. Need to make the job ids unique with appid jobid and the entry id or tag.

**Comment by mohammedzee1000** [comment]
This is a urgent issue, as its affecting openshift, centos and cockpit containers.
