### ISSUE TITLE
Updating job.yml does not reflect changes in ci jobs

### ISSUE THREAD

**Issue by mohammedzee1000** [CentOS/container-pipeline-service#122]
I recently updated the index ci job in the job.yml, based on requirements for dependency validation.

https://github.com/CentOS/container-pipeline-service/pull/118/files#diff-091765ca1f913cb1fc03c4831eb431bbR169

Inspite of this update, the actual job in ci has not been updated, and it still uses the old configuration, while already using the updated script.

This causes the index ci to fail as the installation of python-networkx, as required has not been done.

**Comment by navidshaikh** [comment]
@mohammedzee1000 :  should this be closed ?

**Comment by navidshaikh** [comment]
@mohammedzee1000 : this is fixed, close the issue ?
