### ISSUE TITLE
Builds that get stuck stay in that state for extended time blocking other jobs

### ISSUE THREAD

**Issue by mohammedzee1000** [CentOS/container-pipeline-service#152]
By my experience with rabbitmq containers, it appears some builds which get stuck for a number of reasons, remain in the same state (2 days for rabbitmq container). We should have a timeout followed by restart of the job(s) for certain number of times to ensure this does not happen, and to mark a job as failure in case of retries running out.

**Comment by navidshaikh** [comment]
@mohammedzee1000 @bamachrn  : How do we go further on this ?

**Comment by navidshaikh** [comment]
This issue has become irrelevant now.
