### ISSUE TITLE
Worker containers are not restarted when respective image gets updated

### ISSUE THREAD

**Issue by rtnpro** [CentOS/container-pipeline-service#173]
## Issue

Currently, worker containers do not get restarted when their images are built again. This could be a bug in Ansible that it's not able to detect the changes in the image of a running container and restart it if there's some change. This means that the worker containers will still be using the older container image if it's not manually restarted.

## Fix

- Restart worker containers during provisioning
- Fix probable bug in ansible upstream

**Comment by navidshaikh** [comment]
I am also hit by this issue while re-provisioning. For every re-provisioning, manual steps for this fix need should be run to have correct deployment.

**Comment by mohammedzee1000** [comment]
Agreed, we should do a restart of containers during provisioning

**Comment by navidshaikh** [comment]
@rtnpro This is fixed, right? Please close issue if no more action needed for the issue.
