### ISSUE TITLE
Remove empty /sha256* directories 

### ISSUE THREAD

**Issue by dharmit** [CentOS/container-pipeline-service#177]
Scanner fails to run when empty directories from previously failed scan runs persist on the directory. We need to effectively catch these cases and remove the directories for scanner to avoid getting blocked.

**Comment by navidshaikh** [comment]
should this be part of #182 ?

**Comment by navidshaikh** [comment]
@dharmit : This is fixed. Should this be closed? This is being handled in scanner worker.
