### ISSUE TITLE
Change Dockerfile linter logs' extension

### ISSUE THREAD

**Issue by dharmit** [CentOS/container-pipeline-service#179]
Dockerfile linter logs get stored on NFS with `.log` extension. When this location is accessed via web browser, it immediately prompts to save the logs.

Instead, we can change the extension to `.txt` to prevent such pop-up and view the logs in browser itself.

cc: @navidshaikh

**Comment by navidshaikh** [comment]
build_logs also need to be taken care, presently  build_logs file also has `.log` extension
