### ISSUE TITLE
Add clean install option to deployment

### ISSUE THREAD

**Issue by mohammedzee1000** [CentOS/container-pipeline-service#182]
I think it would be a good idea to have an ansible variable, say clean=True|False, where if it is set, the the scripts will go ahead and clean up the machine of all previous footprints (killing and removing containers, cleaning up openshift volumes, clean out the logs and so on)

**Comment by navidshaikh** [comment]
+1

**Comment by navidshaikh** [comment]
@rtnpro :WDYT ? I can take this up too.

**Comment by navidshaikh** [comment]
We now have cleanup utility for deployments in place. Closing the issue, any subsequent additions to clean up utilities should be added separately.
