### ISSUE TITLE
Send email information to dev users of the pipeline during deploy

### ISSUE THREAD

**Issue by mohammedzee1000** [CentOS/container-pipeline-service#189]
I think it would be a good idea, if emails can be sent out to all users with containers on pipeline whenever there is a deploy happening, that their builds may not get triggered, and possibly requesting them to not push changes during that time, or push a dummy change after the deploy is complete to trigger the builds. 

This could be part of deployment itself, where is the index is read to gather list of notify emails and email is sent out to all of them.

**Comment by navidshaikh** [comment]
I think the better options is to populate all image author's email adresses in index. And sent out a normal (manual) outage email.

**Comment by bamachrn** [comment]
not related now.
