### ISSUE TITLE
Use python-cicoclient for configuring CI nodes

### ISSUE THREAD

**Issue by navidshaikh** [CentOS/container-pipeline-service#198]
python-cicoclient provides shell, python and ansible integration to talk to ci.centos.org , this issue is to track implementing CI script for CCCP using cico client.

References: https://github.com/CentOS/python-cicoclient
https://github.com/almighty/almighty-jobs/blob/master/devtools-ci-index.yaml#L95

**Comment by kbsingh** [comment]
we might actually be able to reduce the code quantify and simplify this entire ci provisioning script by just moving to bash entirely and using the cico command line client.

**Comment by navidshaikh** [comment]
@rtnpro @bamachrn : WDYT?

**Comment by bamachrn** [comment]
CI is now a single job manages few pipeline. so the complexity on node management is simplified
