### ISSUE TITLE
move test index to be a branch of the index itself

### ISSUE THREAD

**Issue by kbsingh** [CentOS/container-pipeline-service#199]
https://github.com/CentOS/container-pipeline-service/blob/master/ci/cccp_ci.py#L102 

this should be removed. 

move the text index to be a branch of the https://github.com/centos/container-index repo itself

**Comment by navidshaikh** [comment]
@rtnpro : PTAL

**Comment by navidshaikh** [comment]
We have `ci` branch for container-index repo itself now. Fixed with PR #377
