### ISSUE TITLE
Why are we tagging test containers with :test and pushing them to r.c.o

### ISSUE THREAD

**Issue by mohammedzee1000** [CentOS/container-pipeline-service#209]
I have noticed that all containers that are built on the pipeline are tagged as test (foo/bar:test) during test phase and are pushed to r.co.

This could become a problem, and is infact is currently a problem as:

1. We are polluting the registry with unnecessary tags.
2. What if a user wants to tag his container with :test, what happens then
3. What about 2 containers of the same namespace. Could that not lead to a clash

To further elaborate my 3rd point, lets say we have 2 containers foo/bar:v1 and foo/bar:v2, and let us assume their build got triggered at about the same time. What happens then. What if v1 pushes test and befroe v2 can consume it, v2 pushes a test container as well. This will especially become a problem at scale.

**Comment by navidshaikh** [comment]
@mohammedzee1000 : do you have a plan to fix it? or should I take it?

**Comment by bamachrn** [comment]
now we do not push extra tags to registry. closing this.
