### ISSUE TITLE
Deletion or renaming of index entries causes orphaned projects

### ISSUE THREAD

**Issue by mohammedzee1000** [CentOS/container-pipeline-service#221]
I have noticed that that if an index entry is removed or renamed (as in appid, jobid or desired tag is altered), in which case the system creates a new project with the new effective name, we end up with orphaned projects in jenkins, as well as openshift. 

Ideally, in such cases, you want all of it to be cleaned up, such as the jenkins and openshift projects, along with possibly the logs what were created for that project namespace.

**Comment by navidshaikh** [comment]
@mohammedzee1000 : Do we know how to fix this or investigation has to be done yet ?

**Comment by mohammedzee1000** [comment]
@navidshaikh The best fix is to delete projects no longer in the index. But that needs to be implemented

**Comment by navidshaikh** [comment]
> The best fix is to delete projects no longer in the index. But that needs to be implemented

alright! 

You want to take it up @mohammedzee1000 ?

**Comment by bamachrn** [comment]
This is implemented in index-reader job sync up and working properly. Closing this.
