### ISSUE TITLE
New architecture graphics for pipeline

### ISSUE THREAD

**Issue by rtnpro** [CentOS/container-pipeline-service#230]
This is an effort to break down the current architecture diagram for CCCP at [1] so that we can:

- have multiple graphics and easy to comprehend for each group of target audience:
  - user
  - pipeline developer/admin
- focus more on content rather than images (we also need to check the license of any image we use)

[1]: https://camo.githubusercontent.com/db737c4c044fd8f30d34c939f5ad1404ec09dd67/68747470733a2f2f646f63732e676f6f676c652e636f6d2f64726177696e67732f642f31734a666e694d7370454b394c4935434f394e736f5358686978624d71594e6f4a6a506939414b484e562d6b2f7075623f773d39363026683d373230

**Comment by rtnpro** [comment]
CCCP for user:


![user](https://cloud.githubusercontent.com/assets/231684/25161919/697a7422-24dc-11e7-9a44-9197d1d873dc.png)

**Comment by rtnpro** [comment]
Architecture:

![architecture](https://cloud.githubusercontent.com/assets/231684/25161941/97df2df8-24dc-11e7-9b44-e63449196c67.png)

**Comment by veillard** [comment]
Very interewsting. Question: there is no way for the user to directly trigger the build without a git push ?

**Comment by rtnpro** [comment]
On Wed, Apr 19, 2017 at 12:46 PM, Veillard Daniel
<notifications@github.com> wrote:
> Question: there is no way for the user to directly
> trigger the build without a git push ?

From user side, no. From admin side, yes, via jenkins UI.

**Comment by bamachrn** [comment]
Closing this in favour of the new openshift based architecture. We are not having separate workers now, instead all the stages in a single build runs in a single pipeline now.
