### ISSUE TITLE
Add logrotate policies

### ISSUE THREAD

**Issue by rtnpro** [CentOS/container-pipeline-service#236]
## Issue

Currently, our log files are just growing and growing. We need to create log rotate policies to rotate logs and purge logs which are no longer in use

**Comment by navidshaikh** [comment]
The span of messages to keep before it rotates has to be considerable to ensure if there is a failed build followed by 100 success builds, we should be able to get the logs.

One of the calculation we can do is have approximate idea of how much logs we export per build and multiply it with twice of number_of_containers_in_index.

This should help ensure we have logs for at least 2 recent builds per containers.
