### ISSUE TITLE
Is exposing Docker socket over tcp really required in scanner node?

### ISSUE THREAD

**Issue by dharmit** [CentOS/container-pipeline-service#250]
In Ansible provisioning for Scanner node, we're exposing the TCP socket. OTOH, we're mounting Docker unix socket on the containers that perform scanning. Can we do away without exposing Docker over TCP socket?

**Comment by navidshaikh** [comment]
There are operations for which we are using connection over TCP socket, for eg: pulling image under test etc.

Check [this set of lines](https://github.com/CentOS/container-pipeline-service/blob/master/beanstalk_worker/worker_start_scan.py#L31-L37), and the connection is used for different operation.

**Comment by dharmit** [comment]
@navidshaikh agreed but that's exactly the piece I'm trying to accomplish using unix socket. [If you check the value of `DOCKER_HOST` variable](https://github.com/CentOS/container-pipeline-service/blob/master/beanstalk_worker/worker_start_scan.py#L16) in the same file, it's `127.0.0.1`. At the moment, I've pushed the change to [this branch](https://github.com/dharmit/container-pipeline-service/tree/fix-250) and will send in a PR if it seems to work well in DevCloud.

**Comment by bamachrn** [comment]
this is no longer relevant as we are running the scanners as a part of the same build pipeline. And we are not using atomic any more.
