### ISSUE TITLE
Create library images for containers in registry.centos.org

### ISSUE THREAD

**Issue by mohammedzee1000** [CentOS/container-pipeline-service#255]
We should have library containers available in registry.centos.org. This will mean someone should be able to pull the centos base image with registry.centos.org/centos:latest, for example.

When we internally push the container from the build system to the registry, it is enough to tag the container as registry.centos.org/centos:latest and then push the same.
So,

`$ docker push internalreg:5000/centos:latest `

is enough to make it a library image within the registry.

We will however, have to designate a container name space, say 'library' to indicate that its a library image, and adopt the pipeline code to appropriately tag and push the image when that namespace is used.

**Comment by bamachrn** [comment]
implemented. library images are available in registry.centos.org now.
