### ISSUE TITLE
Make workers handle beanstalkd restart/failures gracefully

### ISSUE THREAD

**Issue by dharmit** [CentOS/container-pipeline-service#257]
At the moment, if beanstalkd goes crazy i.e. restarts or fails, all the workers go nuts. All workers start logging messages related to connection failure and end up making the log file get really huge in size. Instead, we should make all workers handle the situation gracefully.

ping @rtnpro, you mentioned you'll work on this, right?

**Comment by navidshaikh** [comment]
I think this is fixed when we refactored workers.
