### ISSUE TITLE
RPM Verify Scanner shows incorrect UUID for image

### ISSUE THREAD

**Issue by dharmit** [CentOS/container-pipeline-service#260]
Take a look at results mentioned in [this pastebin](http://pastebin.centos.org/88941/). All scanners show the UUID `f01d499172de41c0a3098628d3d125e054995e7093bc1a9830f08702c9756d00` while RPM verify scanner's results show it as `01d499172de41c0a3098628d3d125e054995e7093bc1a9830f08702c9756d00`

Here's `docker images` output:

```bash
$ docker images --format "{{.Repository}}: {{.ID}}" --no-trunc | grep mattermost-team
registry.centos.org/mattermost/mattermost-team: sha256:f01d499172de41c0a3098628d3d125e054995e7093bc1a9830f08702c9756d00
```
ping @navidshaikh

**Comment by bamachrn** [comment]
@dharmit I believe we can close this now right?

**Comment by dharmit** [comment]
I'm not the assignee on this one. But yes, I guess it's good to close. This is based on old arch so doesn't matter a lot.
