### ISSUE TITLE
Correct the way scan worker logs when it fails to pull an image

### ISSUE THREAD

**Issue by dharmit** [CentOS/container-pipeline-service#264]
Below code logs the scenario wherein scan worker fails to pull the image:

```python
if 'error' in pull_data:
    logger.fatal("Couldn't pull requested image", extra=pull_data)
    return False
```
Argument `extra` expects a dictionary but `pull_data` is a string.

**Comment by navidshaikh** [comment]
@dharmit : is this still relevant ?

**Comment by dharmit** [comment]
I don't think so. Closing it.
