### ISSUE TITLE
Empty /var/lib/atomic after copying data to NFS

### ISSUE THREAD

**Issue by dharmit** [CentOS/container-pipeline-service#267]
At the moment, we copy the scan results generated by various scanners to a NFS share. However, we don't do anything with the scan results stored in original location - `/var/lib/atomic/<scanner-name>`. This piles up and recently lead to issues resulting in no disk space left on the file system.

We should remove the data from `/var/lib/atomic` after a successful scan run so that this pile up doesn't happen.

**Comment by navidshaikh** [comment]
to be fixed by #558
