### ISSUE TITLE
Issue while parent job is building

### ISSUE THREAD

**Issue by bamachrn** [CentOS/container-pipeline-service#271]
In our current service while building a project in builder we first check if it has a depends on. It has a parent container image in its dependency chain. The parent container is either not there or building, then builds checks for the dependency and  keeps the build back in start_build tube.

```bash
if parent_build_running:
         logger.info('Parents in build: %s, pushing job: %s back '
                            'to queue' % (parents_in_build, job_details))
         bs.use('master_tube')
         bs.put(json.dumps(job_details))
```

Now the scenario is, if suppose image1 is in the build worker and image1 depends on image2. image2 is not there in registry, and image1 request is the only one request in build tube. Then image1 checks the dependency and fails and puts the request goes back in the tube after failing. This goes on infinitely and fills up the logs which causes the issue.

**Comment by rtnpro** [comment]
> Now the scenario is, if suppose image1 is in the build worker and image1 depends on image2. image2 is not there in registry, and image1 request is the only one request in build tube. Then image1 checks the dependency and fails and puts the request goes back in the tube after failing. This goes on infinitely and fills up the logs which causes the issue.

The check ``Build(namespace).is_build_running()`` does not care about whether the image is present in the registry or not.

Whenever, we start a build, we touch a file for the project under ``/srv/pipeline-logs`` and delete the file when the delivery phase is complete. In between this, any child image build will be stalled and will be pushed back to the queue. This behavior is expected.

However, the real **issue** is that, when there are no other jobs to build in the build queue apart from the jobs waiting for their parent builds, the workers will keep processing these jobs and will keep pushing these jobs back to the queue. This operation will run 1000s of times a second and will keep generating logs, huge amount of unnecessary logs.

The fix would be to rate limit the retries for build jobs waiting for their parent builds.
