### ISSUE TITLE
Handle openshift not returning build ID when triggering a project build

### ISSUE THREAD

**Issue by rtnpro** [CentOS/container-pipeline-service#276]
Reference: https://github.com/CentOS/container-pipeline-service/blob/master/beanstalk_worker/worker_start_build.py#L128

We do not handle empty build details returned by Openshift and error out. There might be a case that Openshift have triggered the build. A solution could be to wait for the build to come up and exit on timeout.

**Comment by navidshaikh** [comment]
Fixed.
