### ISSUE TITLE
Apply unique job ID in the scope of worker

### ISSUE THREAD

**Issue by dharmit** [CentOS/container-pipeline-service#278]
This was discussed as a part of PR review for #270. Upon failure in handling a job, a worker writes failure message along with the entire job info into the log file. Instead, we can have following flow from the time a worker receives a job:

- worker writes the job details when it receives the job along with a unique job id like we do to create `TEST_TAG`
- this can be `self.job_id` or some such attribute that's limited in scope to a particular worker
- then handle the job it received
- if job is handled successfully
    - log the success info in log file, put job info into the log file along with `self.job_id`
- if job handling fails
    - log failure info along with `self.job_id`

This helps us save disk space when we log entire job info upon failure to handle the job. Ideally, we'd like to implement this in base class so that none of the workers have to bother about its implementation.

**Comment by navidshaikh** [comment]
@dharmit : I think this is fixed. Please close the issue.

**Comment by dharmit** [comment]
Fixed via f7805d3
