### ISSUE TITLE
Streamline key-value pairs across the workers

### ISSUE THREAD

**Issue by dharmit** [CentOS/container-pipeline-service#328]
Starting from Jenkins till the mail server, we keep adding and removing key-value pairs from job info in an alarming and, often, hazardous way causing minor slips to cause not-so-minor issues. For example, a missing key-value pair from linter worker's results prevented mail server from sending mails and thus holding back hundreds of weekly scan emails in production environment.

This issue is planned to be solved in two steps:

- [ ] Initialize the job with all the key-value pairs ever going to be required by all the workers of the service.
- [ ] Write tests to ensure that adding even a single key-value pair at worker level leads to failure and thus encourage devs to add them at top level (Jenkins).

**Comment by navidshaikh** [comment]
@dharmit : I think the issue is fixed ?

**Comment by dharmit** [comment]
Fixed by #339
