### ISSUE TITLE
Setup instructions are out of date

### ISSUE THREAD

**Issue by TomasTomecek** [CentOS/container-pipeline-service#345]
I can't see such files or directories in the repo.

**Comment by mohammedzee1000** [comment]
Thanks for bringing this up, it needs to be fixed.
But you can set it up by using ansible playbook available in https://github.com/CentOS/container-pipeline-service/tree/master/provisions 

Write an inventory file that looks something like this

```
[all:children]
jenkins_master
jenkins_slaves
openshift
scanner_worker

[jenkins_master]
a.a.a.a

[jenkins_slaves]
b.b.b.b

[openshift]
c.c.c.c

[scanner_worker]
d.d.d.d

[all:vars]
cccp_index_repo=https://github.com/mohammedzee1000/test_index.git
beanstalk_server=c.c.c.c
copy_ssl_certs=True
oc_slave=b.b.b.b
jenkins_public_key_file=/path/to/cccp-jenkins.pub
jenkins_private_key_file=/path/to/cccp-jenkins
public_registry=b.b.b.b
test=True
intranet_registry=b.b.b.b:5000
setup_nfs=True
test_nfs_share=d.d.d.d:/nfsshare
deployment=test

```
And then, while having repo root as current working directory, run the following:

`ansible-playbook provisions/main.yml -u root -i <path to inventory file>`

**Note :** 
1. The nodes have to be centos, with root access over ssh.
2. You must create ssh keys which should be a single time operation and provide path to jenkins_public_key and jenkins_private_key.

**Comment by TomasTomecek** [comment]
Ehm, what are all of those `a.a.a.a` and `b.b.b.b`: does it meant that I have to set up like 8 other services myself?

**Comment by mohammedzee1000** [comment]
No, you need nodes. It can be a single node, just make sure you give enough RAM as both jenkins and openshift will be brought up. 
a.a.a.a, b.b.b.b etc are the ip addresses of the nodes where the pipeline will be setup. For example a.a.a.a could be a node having ip 192.168.121.10 where the jenkins master will be setup.

**Comment by bamachrn** [comment]
Architecture updated, we are using openshift-ansible to setup the cluster now.
