### ISSUE TITLE
Add centos-ci as a collaborator

### ISSUE THREAD

**Issue by rtnpro** [CentOS/container-pipeline-service#35]
Add ``centos-ci`` user as a collaborator for this project to enable Github Pull Request Builder integration with ci.centos.org.

Doc to be followed for setup: https://wiki.centos.org/QaWiki/CI/GithubIntegration#head-c87fef7295be7a4d0658f4be65adb68d8f3e3861

@kbsingh @bamachrn ^^

**Comment by kbsingh** [comment]
let me know once you have the integration work done and tested in jenkins on ci.centos.org

**Comment by kbsingh** [comment]
this should have been done already, reopen if there are issues.
