### ISSUE TITLE
Install and configure dependencies on slave for atomic scan

### ISSUE THREAD

**Issue by dharmit** [CentOS/container-pipeline-service#38]
Install/configure below dependencies of atomic scan on the worker nodes at the time of ansible provisioning:

- [x] atomic
- [x] docker image: registry.centos.org/pipeline-images/pipeline-scanner
- [x] `atomic install` the image

**Comment by kbsingh** [comment]
applying by hand for now since this instance isnt managed by ansible.

**Comment by kbsingh** [comment]
we will need to factor this into the scale out for the scanner infra.

**Comment by bamachrn** [comment]
Scan worker is moved to vm itself and provisiong added to ansible
