### ISSUE TITLE
Adding Clair / vulnerability static analysis

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#393]
CCCP is already checking for outdated RPM's, python packages, etc. using atomic scan.

Checking security vulnerabilities should be added too (https://github.com/coreos/clair)

Recently, Docker Hub added vulnerability analysis to all containers being pushed to the repository, however, you'll have to pay for a private repository to use it. (https://docs.docker.com/docker-cloud/builds/image-scan/)

**Comment by dharmit** [comment]
We didn't use Clair because it uses RHEL CVE database for CentOS. It's not recommended to use same DB as RHEL. We might end up triggering false positives.

**Comment by cdrage** [comment]
@dharmit Clair's quite popular within the Docker community, it'd be a shame to not have it included within CCCP. 

Isn't using the RHEL CVE database a *good* thing? I wasn't able to find any documentation online regarding not recommending using the RHEL CVE with CentOS. Besides, their both RedHat-based systems. :+1: 

I know I'd be very grateful to see what security vulnerabilities my Docker containers have.

Clair even has native-support for CentOS: https://github.com/coreos/clair/blob/eb5be923057af8277fbd6bf9de4d14cbaa181a78/ext/featurens/redhatrelease/redhatrelease.go

**Comment by dharmit** [comment]
Having security vulnerability scanning is something we'd like to have as well. But using RHEL CVE database for it won't be 100% accurate. That's why we didn't go down that route. 

However, we can reopen this discussion with @kbsingh and see if vulnerability scanning can be provided as well. And if using RHEL CVE database would suffice or should we look to get a CentOS CVE database. I agree it would add value to what we already do!

**Comment by cdrage** [comment]
@dharmit You're able to customize what Clair reads / ingests as their CVE database :100:

**Comment by cdrage** [comment]
To update, I've ran about 10-15 containers through Clair from the https://registry.centos.org database.

Amazingly, I haven't even encountered **one** vulnerability yet. It seems that container-pipeline-service has been doing an amazing job of keeping everything updated.

**Comment by bamachrn** [comment]
closing this. We can re-think on getting things over quay.io and complementing them with the feature. Lets track it in a different place.
