### ISSUE TITLE
Using Kubernetes instead of OpenShift

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#396]
Is there a possibility of using Kubernetes as an alternative to OpenShift for CCCP? Or does CCCP rely on the ability of building containers (BuildConfig, etc.) feature of OpenShift?

**Comment by dharmit** [comment]
We do rely on Build Configs to build containers. :smile:

**Comment by bamachrn** [comment]
Now we have moved to OpenShift pipeline based builds fully. It is completely dependent on BuildConfigs and jenkins pipeline. Closing this.
