### ISSUE TITLE
Website / GitHub authentication

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#408]
I have some thoughts on adding a website for CCCP.

First off, having a general website where it clearly explains CCCP would be great. I've built http://kompose.io as well as http://kedgeproject.org which has outlined both Kubernetes projects quite well, and doing the same for CCCP would help immensely. 

However, in the grandeur of things, what about GitHub authentication in order for users to easily add a project to CCCP / registry.centos.org ?

Rather than having to add `cccp.yaml` as well as go through the documentation, it's as simple as logging in (after authenticating with GitHub) and enabling it for your repository. This is similar to Docker Hub, but of course, all of this is being built on open-source tools rather than something proprietary. 

You'd see the builds being done immediately as well as be notified when they go wrong. Similarly to how it works with Coveralls, SemaphoreCI, etc. Being notified that tests pass (analyzing the actual container). As well as pushing said container to the correct docker registry. For example, what coveralls for your repo? It's as simple as logging into the coveralls.io website, enabling it for your repo, and BAM, everything is done. Same could go for CCCP but **much** better.

Just some thoughts :100:

**Comment by bamachrn** [comment]
@cdrage thanks for thinking in this route. its great idea to bring one website for CCCP. But in our case we want to broadcast https://registry.centos.org as registry for centos. pipeline is a way to get in there, but not the actual service we are focussing. How about putting pointers/ entry points to [container-index](https://github.com/centos/container-index.git) from the [registry ui](https://registry.centos.org) itself? At the moment we are in very initial stage for the UI though. We are working for improving this to make a single point of interaction.

**Comment by bamachrn** [comment]
This would be solved with a common API based UI with real time build logs and status. This is kind of work in progress.
