### ISSUE TITLE
https://registry.centos.org link needs to be added to GitHub repo

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#413]
https://registry.centos.org should be added under "settings" of this GitHub repo so there's a direct link to the website :+1:

**Comment by mohammedzee1000** [comment]
@cdrage do you mean in the top description?

**Comment by cdrage** [comment]
@mohammedzee1000 Yup, it's not listed. And any documentation to registry.centos.org within the README isn't [linked](https://register.centos.org)

**Comment by mohammedzee1000** [comment]
@kbsingh can you do the same, and edit the repository title to include registry.centos.org link.

**Comment by bamachrn** [comment]
done.
