### ISSUE TITLE
Bug on listing all containers on https://registry.centos.org/repositories

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#414]
Using the "page/all" button the bottom of https://registry.centos.org/repositories/ does not actually show ALL containers.

Steps to reproduce:

 1. Go to https://registry.centos.org/repositories/
 2. Scroll down and click on "Show all" under page
 3. Does not actually Show All and you still have to go to the next page to view everything.

Ping @kwk

**Comment by kwk** [comment]
How was the container started that runs the frontend? Might be related to this section: https://github.com/kwk/docker-registry-frontend#default-tags-per-page

**Comment by mohammedzee1000** [comment]
@kwk https://github.com/CentOS/container-pipeline-service/blob/master/provisions/roles/registry/tasks/main.yml#L16

**Comment by kwk** [comment]
Hm that's odd. @cdrage how urgent is this?

**Comment by cdrage** [comment]
@kwk Not urgent, just something I encountered.

**Comment by bamachrn** [comment]
@cdrage fixed it with a new registry-ui. closing this.
