### ISSUE TITLE
README should contain up-to-date communication chat room

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#415]
#centos-dev is on IRC is quite active and may not be the best place to reach maintainers of CCCP.

https://chat.openshift.io/developers/channels/container-apps is a publicly accessible channel and should be noted as the main chat / support room for CCCP :+1:

**Comment by bamachrn** [comment]
implemented PR: https://github.com/CentOS/container-pipeline-service/commit/88290ee551f22e4f463e25d1cb215e00c6eece5e#diff-04c6e90faac2675aa89e2176d2eec7d8 closing this.
