### ISSUE TITLE
TODOs for documentation, site, emphasizing importance of the registry

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#417]
Here is a brief outline of what could be improved as I've worked through the documentation as well as going through (some) of the code.

Site:

- [ ] Complete redesign of https://registry.centos.org Using a similar format as: http://kedgeproject.org (previous site redesign I did, obviously won't be the exact same format, but the site is a general gist of improvements we did for improving user ingress). Outlining what the project is about, installation (if you want to run it bare metal, obviously it's not very important as actually using the registry)
- [ ] Converting current documentation to using `slate` file reference, similar to: http://kedgeproject.org/file-reference/ for easier consumption / using `cccp.yaml` and configuration
- [ ] Central location for documentation and "getting started". As of right now, this is split between https://github.com/CentOS/container-index and https://github.com/CentOS/container-pipeline-service
- [ ] Redesign / updates to https://registry.centos.org/repositories/20 to list all containers / emphasize some important ones being used (OpenShift?)
- [ ] More CentOS logos / emphasis that this is a Docker Registry 
- [ ] Imagery! Text-galore at the moment on http://registry.centos.org as well as GitHub pages
- [ ] Emphasis on what this project is about. It has been difficult (at least for me) to actually understand what this project does and WHY it's important. For example: https://registry.centos.org/ has little explanation on what the registry actually is. Even a ctrl+f for docker only shows two mentions of it and it relates to configuration. This means to be clear to the user what this does.
- [ ] Emphasizing the benefits (number one: analysis and automatic pushing + building!! best feature of cccp and yet there's little mention of it) 

Documentation on https://github.com/CentOS/container-index and https://github.com/CentOS/container-pipeline-service :

- [ ] Update README.md for https://github.com/CentOS/container-index to have properly formatted YAML and/or tables for what variables can be used in `cccp.yaml`
- [ ] Update https://github.com/CentOS/container-pipeline-service README.md (spelling errors, grammar, possible updates to diagram). Clean-up convoluted wording and simplification. 
- [ ] Synced documentation between `/docs` folder on GitHub to the website (TravisCI deployment using https://gist.github.com/rondy/af1dee1d28c02e9a225ae55da2674a6f )
- [ ] Splitting of documentation into separate files for clearer outlining (for example, adding actual installation instructions for bare metal deployment to a separate file rather than the README.md) Also, adding a "quick-start" guide.

Epics for site / CCCP / outside-scope-of-documentation:
- [ ] Better GitHub integration (login as GitHub user, automatically adding your repo to cccp.yaml rather than having to do a PR request)
- [ ] GitHub notifications / mentions / GitHub-bot (similar to Coveralls bot, Jenkins bot: https://github.com/fabric8-updatebot)
- [ ] 100% on OpenShift for deployment

I'll add more as I go, but this is a general outline of improvements.

**Comment by bamachrn** [comment]
Most of the parts were done. We can re-think/re-open issues on rest of the points. closing this
