### ISSUE TITLE
Confusion over setup

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#421]
Okay, so we've got the ansible playbooks which are *great*.

However...

What is the underlying host OS that needs to be available?

Does it automatically configure an OpenShift host / Jenkins master / Jenkins Slave or do you already have to have one setup?

**Comment by bamachrn** [comment]
so the current ansible script we have, sets up all the four nodes from zero to run the service. we just need four machines/VMs and have `ssh, sudo` access.

**Comment by cdrage** [comment]
@bamachrn That isn't true. If I have Debian setup or Ubuntu, setting up CCCP won't work.

See: https://github.com/CentOS/container-pipeline-service/blob/master/provisions/main.yml#L14

We will have to specify that CentOS or Fedora would be required.

**Comment by bamachrn** [comment]
Ah! yes, did not think on that front, yes, we are aiming for CentOS based images.

**Comment by cdrage** [comment]
@bamachrn So what version of CentOS is CCCP compatible with? Has this been tested against Fedora as well?

**Comment by bamachrn** [comment]
@cdrage we have tested/ built CCCP in CentOS 7. it works with Fedora as well, at least till Fedora-25 we have tested.

**Comment by bamachrn** [comment]
We moved to openshift based architecture. Setup is managed by [openshift-ansible](https://github.com/openshift/openshift-ansible) repo. closing this.
