### ISSUE TITLE
`vagrant.yml` in Ansible setup

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#422]
Shouldn't this be `main.yaml`? https://github.com/CentOS/container-pipeline-service/tree/master/provisions

See: https://github.com/CentOS/container-pipeline-service/blob/master/README.md#setting-up-the-pipeline-service

```sh
# Provision the hosts. This assumes that you have added the usernames,
# passwords or private keys used to access the hosts in the hosts file
# above
$ ansible-playbook -i hosts vagrant.yml
```

**Comment by bamachrn** [comment]
yup, thanks for figuring out. this has to be updated

**Comment by cdrage** [comment]
I've updated this in my README updated https://github.com/CentOS/container-pipeline-service/pull/423

**Comment by bamachrn** [comment]
colsing this
