### ISSUE TITLE
Name of scanner container images and their namespace

### ISSUE THREAD

**Issue by navidshaikh** [CentOS/container-pipeline-service#43]
I am creating this issue to discuss what should be the naming convention for the atomic scanner names and the namespace should be used to group the scanners.

With scanning and introspection efforts to know more about containers, we are going to have a set of atomic scanner container images, if we can discuss and devise a naming convention to name the atomic scanners and their namespace.

**Proposal 1:**
For scanner container images, proposing `scanner-<scanner-name>`. 

Example: 
For a scanner doing rpm verify test in given container image, the name of the container image would be
`scanner-rpm-verify`.

Name of the namespace to bucket all the individual scanners,
Proposing `atomic-scanners` as the namespace for hosting of all the atomic scanners at registry namespace.

**Proposal 2:**
Namespace: `atomic-scanners`
name of the scanner container image: `<scanner-image>`

Example:
`atomic-scanners/rpm-verify`

Decide a namespace and naming convention for the atomic scanners, the atomic scanner images will have coherent names across different public / private registries.

Example:
registry.centos.org/atomic-scanners/rpm-verify
docker.io/atomic-scanners/rpm-verify

**Comment by navidshaikh** [comment]
ping @rhatdan @solidaridirk @aweiteka @vbatts, would like your recommendations as well.

**Comment by rhatdan** [comment]
@baude @mpreisler PTAL

**Comment by rhatdan** [comment]
@baude what is the current name for the scanning containers?  Each container can have multiple scan types, and currently we allow them to define their own.

**Comment by rhatdan** [comment]
This would be good to invite blackduck engineers for this discussion also.

**Comment by baude** [comment]
There is no convention for naming.  It would probably be good to generate a discussion around that.  One concern I have related to this is right now atomic assumes anything in /etc/atomic.d is a scanner.  So naming convention should probably encompass that too.

**Comment by vbatts** [comment]
Is this name just an annotation/label in a config somewhere? Or is itself a filename? Is there a requirement that the name map to a resolvable resource (container image or URL)?

**Comment by navidshaikh** [comment]
> One concern I have related to this is right now atomic assumes anything in /etc/atomic.d is a scanner. So naming convention should probably encompass that too.

Does this mean the naming convention for configuration file itself ?

**Comment by navidshaikh** [comment]
> Is this name just an annotation/label in a config somewhere? 

Name of the scanner is specified in a configuration file, and included in the scanner container image itself.
Example:
```
 type: scanner
 scanner_name:
 image_name: fully-qualified image name
 default_scan:
 custom_args: [optional]
 scans: [
      { name: scan1,
        args: [... ],
        description: "Performs scan1"},
      { name: scan2,
        args: [...],
        description: "Performs scan2"
 }
 ]
```
> Or is itself a filename?
No.

>  Is there a requirement that the name map to a resolvable resource (container image or URL)?

AFAIK, user of scanner needs to know the (atomic scanner) container image name / URL. User pulls the image, installs it, list the scanner and runs accordingly.

@baude wrote a nice [blog](http://developers.redhat.com/blog/2016/05/20/creating-a-custom-atomic-scan-plug-in/) on writing the custom scanner.

**Comment by navidshaikh** [comment]
I think, along with discussing the atomic scanners container image names, we should also discuss about the scanner names themselves (atomic scan --list) and probably configuration file as well.
