### ISSUE TITLE
Tag CCCP releases

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#441]
We should tag periodic releases of the container pipeline service and push them to GitHub, instead of building straight from dev.

**Comment by bamachrn** [comment]
@cdrage we had a long discussion around this. Our plan is master branch is always deployed in prod. And we want to make sure master is never broken. So we parked the idea of tagging repo. If we get into position of doing quick deployment and roll-back if required. For now we maintain a log for the commits deployed in prod.

**Comment by bamachrn** [comment]
this is managed by openshift rolling update, so anything in the branch is deployed in the nest run of seed-job after the slave image is built.
