### ISSUE TITLE
Logs should be outputted to a better location

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#445]
I just received my first email after my container was built that links to: https://registry.centos.org/pipeline-logs/ZGE3NWZmMmIzMT/

This information is AWESOME. But it's *very* hard to retrieve or grep if using an outside service..

For example, what if I wanted to get the current build logs?

I'd have to retrieve this random "ZGE3NWZmMmIzMT" character from my e-mail and go to the link.

Rather than these characters, the logs should be outputted (and override and previous logs), for example (using `cdrage/mosh-centos7:latest`) to: https://registry.centos.org/pipeline-logs/cdrage/mosh-centos7/latest

This makes it a lot easier for outside services (perhaps future CLI commands?) or websites to easily grep the information and consume it.

**Comment by navidshaikh** [comment]
> But it's very hard to retrieve or grep if using an outside service

For now I think the anticipated workflow is, user will click links in build notification email.

> Rather than these characters, the logs should be outputted (and override and previous logs), for example (using cdrage/mosh-centos7:latest)

There are cases where the `appid` (cdrage) and `jobid` (mosh-centos7) changes. Also, overriding logs of just previous build could raise questions like "Hey, I wanted to check the logs for an earlier build?"

Some context around random characters like "ZGE3NWZmMmIzMT"
 - We wanted to have a logs directory for users to look at build results
 - and build directory to contain
     - build / test / delivery logs
     - scanner results
     - Linter results
      - or even Dockerfile (in future)

> This makes it a lot easier for outside services (perhaps future CLI commands?) or websites to easily grep the information and consume it.

Agreed about client-side services making use of the build artifacts, however, I think it's better if we could plan to serve these details using API like interface.

We have the database in place, logging verbose information in place, also [this work](https://github.com/CentOS/container-pipeline-service/pull/372) done by @mohammedzee1000 to serve build related details for UI.

**Comment by mohammedzee1000** [comment]
Yea, we could do that with the api, allow users to access the logs over the API. Infact this is already a use case i planned the API for. Not just for our UI, but for end users as well. 

i do want to get to a point where a user could display information about their container builds on their own websites etc if they want to. 

But for now, the immediate target is the registry UI itself

**Comment by cdrage** [comment]
@mohammedzee1000 Yeah, the reason being having a good directory is so I can actually grep the information regarding the build for the registry UI.

Your work on the API will help immensely since we'll be able to retrieve and view information on the build online :100:
