### ISSUE TITLE
Remove all hardcoded variables

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#453]
CCCP should work no matter what registry you use. At the moment, there are multiple references to registry.centos.org in the configuration scripts.

For example: 
 - [ ] https://github.com/CentOS/container-pipeline-service/blob/master/provisions/group_vars/all#L10 should point to https://github.com/CentOS/container-pipeline-service/blob/master/provisions/roles/nginx/templates/registry.centos.org.conf.j2#L32

**Comment by bamachrn** [comment]
This is fixed with the new openshift-ansible based ansible inventory. Also we are not resetting the openshift cluster in each deployment now. We are just doing rolling update for the service running on top of the openshift cluster.
