### ISSUE TITLE
Private keys?

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#454]
Came across this earlier, but should this be public?

https://github.com/CentOS/container-pipeline-service/blob/master/provisions/roles/nginx/templates/ssl_nginx.key.j2

**Comment by bamachrn** [comment]
These files are not the actual ones we use for registry.centos.org. These were kept for testing the registry in a test setup, where we do not need valid certs.

**Comment by cdrage** [comment]
@bamachrn can you re-open the issue since it's still odd to have those private and public keys there without any notes / indication of what they're for.

**Comment by mohammedzee1000** [comment]
True, reopened the same.

**Comment by bamachrn** [comment]
This is removed in the openshift based architecture
