### ISSUE TITLE
Add support for OCI compliant images

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#457]
Add support for OCI compliant images. Specifically, images built by `buildah`.

**Comment by mohammedzee1000** [comment]
That would be really cool feature to have.

**Comment by dharmit** [comment]
I honestly don't know what "OCI compliant image" is supposed to mean. Isn't that a really broad term referring to https://github.com/opencontainers/image-spec? Can we please note down the specifics that we are looking for here by way of "OCI compliant images"?

**Comment by cdrage** [comment]
@dharmit It means any image that is OCI compliant can / should be able to push to the CentOS registry.

https://github.com/opencontainers/image-spec is the spec, in the future, we should support it. 

It's vague since it's a spec... but any tool (such as `buildah`) would be able to push the OCI-compliant image as long as we support the spec.
