### ISSUE TITLE
Way too many emails (add ability to disable successes)

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#458]
Is there a way to disable SUCCESS emails being sent and only FAILURE?

Even with only two containers, I've received quite a few emails for each re-build.

**Comment by bamachrn** [comment]
Not yet, but lets lets get an option for users to disable the success emails.

**Comment by navidshaikh** [comment]
Received a failure email, a user might also want to check build logs for the last successful build. We need to think about availing that too.

**Comment by tmds** [comment]
I got more e-mails this week. "Weekly scanning results for image", 1 mail per image.
