### ISSUE TITLE
Unable to set rsync_ssh_opts

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#463]
Setting rsync options here: https://github.com/CentOS/container-pipeline-service/blob/master/provisions/hosts.sample#L27 does not work due to https://github.com/CentOS/container-pipeline-service/blob/master/provisions/group_vars/all#L3 being blank.

https://github.com/CentOS/container-pipeline-service/blob/master/provisions/group_vars/all#L3 line needs to be removed completely

**Comment by navidshaikh** [comment]
Fixed in #506 
Edit group_vars/all file to update rsync options before provisioning.
