### ISSUE TITLE
Provisions fail due to point at localhost:8080 for Jenkins check

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#478]
Jenkins check fails due to looking at localhost:8080 rather than {JENKINS-MASTER-IP}:8080

See: 
https://github.com/CentOS/container-pipeline-service/blob/master/provisions/roles/jenkins/master/tasks/main.yml#L34
and
https://github.com/CentOS/container-pipeline-service/blob/master/provisions/roles/jenkins/master/tasks/main.yml#L16

**Comment by navidshaikh** [comment]
Since the task is supposed to run on `jenkins_master` node itself.
https://github.com/CentOS/container-pipeline-service/blob/master/provisions/main.yml#L135

what are the scenarios, if task is running on same node, and JENKINS_MASTER IP is desired instead of `localhost` reference?

**Comment by cdrage** [comment]
@navidshaikh It doesn't make any sense that `localhost` is listed, it should be testing against the actual JENKINS_MASTER_IP.

The ansible-playbook is being ran on whatever development machine you're on and pointing towards jenkins master, slave, etc. Running it on an actual node that is going to be provisioned doesn't make sense. So testing it against `localhost` wouldn't actually work because you're not deploying it against your development machine / local dev environment running ansible-playbook.

**Comment by cdrage** [comment]
Closed via #491
