### ISSUE TITLE
EOF errors in pre-prod environment

### ISSUE THREAD

**Issue by dharmit** [CentOS/container-pipeline-service#483]
We're seeing EOF errors in pre-prod while pulling images through imagescanner or scanner worker. But we don't see that in prod. 

Is this because of different versions in both environments for `docker-distribution`?

**Comment by navidshaikh** [comment]
> Is this because of different versions in both environments for docker-distribution?

For pre-prod:
```
$ rpm -q docker-distribution
docker-distribution-2.6.2-1.git48294d9.el7.x86_64
```

@bamachrn can you confirm about version for prod env?

**Comment by bamachrn** [comment]
@navidshaikh both are same 
```
$ sudo rpm -q docker-distribution
docker-distribution-2.6.2-1.git48294d9.el7.x86_64
```

**Comment by dharmit** [comment]
Looks like pre-prod redeployment fixed this for us? Should we close this?
