### ISSUE TITLE
integrating with nexus registry

### ISSUE THREAD

**Issue by stainles** [CentOS/container-pipeline-service#487]
Hi Guys, I really happy use your project for build container,I have one question.

I use in my company the nexus registry for docker images and  I cant use nexus without authorisation.

How or where I can change or write changes for authorisation on nexus (I mean docker login or use the config.json for it)?

Sorry for my English.

here log:

```
==> Pulling tested image (172.30.233.30:5000/864a2288f25bcb627071883a4a653627e86403f1f8714c33d1c40abb/bind:test)
--
  | Trying to pull repository 172.30.233.30:5000/864a2288f25bcb627071883a4a653627e86403f1f8714c33d1c40abb/bind ...
  | test: Pulling from 172.30.233.30:5000/864a2288f25bcb627071883a4a653627e86403f1f8714c33d1c40abb/bind
  | Digest: sha256:48db9e35dcd69a39d835bc113fc7d9793f76ae25f444dee2aa98a6b28ce41971
  | ==> Re-tagging tested image (172.30.233.30:5000/864a2288f25bcb627071883a4a653627e86403f1f8714c33d1c40abb/bind:test -> nexus-test.local:8443/centos/bind:Nzg3MDAzNDI0Zj)
  | ==> Pushing the image to registry (nexus-test.local:8443/centos/bind:Nzg3MDAzNDI0Zj)
  | The push refers to a repository [nexus-test.local:8443/centos/bind]
  | 354368e8f078: Preparing
  | 5cfa84b5b94b: Preparing
  | 753f0851d0ab: Preparing
  | 10624caf35d3: Preparing
  | unauthorized: access to the requested resource is not authorized
```

**Comment by bamachrn** [comment]
Hi @stainles not sure if I have understood your question properly. It seems you have got the setup of server but it is failing to push the built image to nexus registry for running the scan job, then finally pushing it to the registry with desired tag. 
In our case we do it by using internal networking of the registry, which allows us to push it directly without authentication from the service system. Now, if you require a login to registry you would need to set the `docker config.json` in the openshift machine where this delivery stage runs. 
One more question, are you trying to build some thing on-premise? I mean why dont you get your containers built in our service and get them delivered to https://registry.centos.org. Raising a PR to [container-index](https://github.com/centos/container-index.git) would be enough for this.

**Comment by mohammedzee1000** [comment]
Thanks @stainles for that. We are happy to hear that you found our project useful :)
