### ISSUE TITLE
registry URL does not match image URL

### ISSUE THREAD

**Issue by bamachrn** [CentOS/container-pipeline-service#495]
I am trying to access the caddy server from the UI and the URL is below
https://registry.centos.org/repo/caddyserver/caddyserver 

but the image for this located at 
```
registry.centos.org/caddyserver/caddyserver
```
hitting the image url gives 404.

can we think of a way to remove `/repo/` from the UI url, that way we make the image url and ui url same.
@cdrage how do you think about this?

**Comment by cdrage** [comment]
@bamachrn Yeah, we could make this change. I'll make an update to the `reg` docker container

**Comment by bamachrn** [comment]
this is done
