### ISSUE TITLE
Sprint 146 Priorities

### ISSUE THREAD

**Issue by bamachrn** [CentOS/container-pipeline-service#510]
- [x] Integrate Analytics API server with scanners to get the non RPM images scanned.

- [ ]  Get API to show data on UI about current build status and logs

- [x]  Enhance UI to show proper tag in the pull command

- [ ]  Allow Users to opt for not receiving success mail and receive only failure emails

- [ ]  Allow users to opt for their images to be in RPM update or not

- [x]  Get Jenkins and Build worker to work in openshift with dynamic scaling.

**Comment by cdrage** [comment]
@bamachrn The "enhance UI" is completed, see: https://github.com/cdrage/reg/commit/2ddae5e2b829a78cd62e02040a362ef9bb981451

Next re-deployment of CCCP should show the changes.

**Comment by bamachrn** [comment]
@cdrage Awesome!

**Comment by bamachrn** [comment]
sprint closed
