### ISSUE TITLE
Upgrade gc to delete image revisions in registry and add pagination

### ISSUE THREAD

**Issue by mohammedzee1000** [CentOS/container-pipeline-service#515]
The GC needs to be updated to 

1. Add pagination, so that dynamic growth of registry does not affect how many images are removed
2. Delete image revisions. Basically, all tagged latest images in the registry receive 2 tags, one by named tag, and another by a sha256 manifest. Currently, only tags are cleared, hence the manifest ref to said layers remains.

**Comment by bamachrn** [comment]
PR merged
