### ISSUE TITLE
pipeline-scanner fails to scan rhel based images with Read-only file system error

### ISSUE THREAD

**Issue by navidshaikh** [CentOS/container-pipeline-service#537]
pipeline-scanner mounts image under test at `/scanin` dir and performs `yum -q check-updates --installroot=/scain/<hash>` operation.
The operation is failing with
```
[Errno 30] Read-only file system: '/scanin/6fe46a33a57749b352ed567eb9b330f381d9a2efd2aaaccb4c221a2e8cc9ca83/etc/yum.repos.d/redhat.repo'
Cannot open logfile /scanin/6fe46a33a57749b352ed567eb9b330f381d9a2efd2aaaccb4c221a2e8cc9ca83/var/log/yum.log
ovl: Error while doing RPMdb copy-up:
[Errno 30] Read-only file system: '/scanin/6fe46a33a57749b352ed567eb9b330f381d9a2efd2aaaccb4c221a2e8cc9ca83/var/lib/rpm/.dbenv.lock'
Could not create lock at /scanin/6fe46a33a57749b352ed567eb9b330f381d9a2efd2aaaccb4c221a2e8cc9ca83/var/run/yum.pid: [Errno 30] Read-only file system: '/scanin/6fe46a33a57749b352ed567eb9b330f381d9a2efd2aaaccb4c221a2e8cc9ca83/var/run/yum.pid' 

Can't create lock file; exiting
```

**Comment by navidshaikh** [comment]
Logged issue at `projectatomic/atomic` repo https://github.com/projectatomic/atomic/issues/1212

**Comment by dharmit** [comment]
How are you mounting the rootfs of the container? Do you give it the `rw` option? Performing `yum` operation will require you to have `rw` permission. In the service, it's covered at https://github.com/CentOS/container-pipeline-service/blob/7ba715583b724f2febb8cff1c0a9257eaa706f6e/container_pipeline/scanners/pipeline.py#L50

**Comment by navidshaikh** [comment]
> How are you mounting the rootfs of the container?

I did not perform any manual operation. Rebased pipeline-scanner on RHEL base image and ran it against another RHEL based image under test. All the operations pipeline-scanner performs stays same. We might need to check the behavior of scanner with RHEL based images.

**Comment by dharmit** [comment]
I'm assuming that you tried to perform the steps in the [description](https://github.com/CentOS/container-pipeline-service/tree/master/atomic_scanners/pipeline-scanner#atomic-scanner-pipeline-scanner) and they worked. But they're not working when the scanner's used via the pipeline.

Is that right?

**Comment by navidshaikh** [comment]
Thanks @dharmit for input.
I was not mounting the image on host machine before invoking the scanner. The scanner works as expected now. :+1:
