### ISSUE TITLE
misc-package-update scanner fails to remove container after scanning

### ISSUE THREAD

**Issue by dharmit** [CentOS/container-pipeline-service#544]
The way container deletion is coded in misc-package-update scanner, if something fails in before code execution reaches that point, we fail to remove the container. Hence leaving behind dangling containers but in run state. This is preventing their container images from being deleted and storage getting quickly filled up.

Code in question: https://github.com/CentOS/container-pipeline-service/blob/4eb8e56823800b184cbedbfcaa93f0b9773ff0a9/atomic_scanners/misc-package-updates/scanner.py#L200

Container removal code is at the end of `try` block so if anything fails before that, container removal doesn't happen. This should move to `finally` block. 

@navidshaikh maybe we should move this to wrapper? Scanners are just meant to do scanning. Anything that's required to setup environment or cleanup the environment should go in wrappers, no?

**Comment by navidshaikh** [comment]
Figured one more issue - Images under test having `entrypoint` defined, the scanner wont be able to create container as it uses `tail -f /dev/null` command to keep container alive, however this command is appended to `entrypoint` in container, which fails.

**Comment by dharmit** [comment]
Not sure i understand this clearly. But having `tail -f /dev/null` as the command to start container did work OK for us in the past for quite some time. Am I misinterpreting what you've said here?
