### ISSUE TITLE
Scan worker needs improvements

### ISSUE THREAD

**Issue by navidshaikh** [CentOS/container-pipeline-service#550]
The current scan worker invokes atomic scanners. Each atomic scanner needs a wrapper, a) invoke the scanner, b)grab the results file path from stdout, c) cleanup. The scan worker invokes a wrapper script per scanner. The wrapper scripts and scan worker itself needs improvements to be able to have a) better control over flow, b)DRY wrappers, c) better clean up process. 

Beside that, the atomic scanners themselves would need refinements.

Tasks
- [x] DRY wrappers per atomic scanner
- [x] Cleanup mechanism to clean residues post scan
- [x] Clean the default location of atomic scan results in /var/lib/atomic, remove the redundant files post scan
- [x] #267 
- [x] #504 
- [x] #176 
- [x] Update scanner functional tests to expect result from all configured atomic scanners

**Comment by dharmit** [comment]
Before we start coding on this, I'd recommend we decide what's going to be in the scope of what. And how things would look/change as we move to OpenShift based environment. 

* **Who sets up the environment**: We need to figure if we want to do setting things up in worker or scanner. For example: if a scanner needs a volume mounted somewhere or, if a scanner needs a container of the image under test started, do these operations get performed by the scanner itself or by the worker? 
* **Who does the cleanup**: Same as above. Do we want scanners to do cleanup or the worker to do it?
* **Fix the scope**: What does a scanner, a wrapper and a worker do? Do we *need* all three of these? Can we reduce? Do we need one more?
* **API based architecture**: Do we want to expose scanners only via API in that, an API call would return results of the scanners for image under test.
* **Containerize atomic scanners**: Is it possible to containerize all scanners and run them from inside a container running on OpenShift? What privilege does such a container need? What volumes (socket, directories) does it need to perform its task? How does containerizing scanners impact the overall flow of things?
