### ISSUE TITLE
library centos image not showing up in registry UI

### ISSUE THREAD

**Issue by navidshaikh** [CentOS/container-pipeline-service#552]
`https://registry.centos.org/centos/` returns 404 while `docker pull registry.centos.org/centos` works.

**Comment by cdrage** [comment]
@navidshaikh Yeah, https://registry.centos.org/centos/centos works, but obviously not https://registry.centos.org/centos I'll push a fix.

**Comment by cdrage** [comment]
Fixed in https://github.com/cdrage/reg/commit/6c4e5e2e18d9f3773165fc1180ebcb0fe69023ca next deployment of the registry and it'll be fixed :+1:

**Comment by navidshaikh** [comment]
> next deployment of the registry and it'll be fixed 👍

Maybe we should leverage the containerized deployment of registry-ui by just restarting the ui container after docker pull. Since this is a user-facing bug fix, and we don't need full-service redeployment.
ping @bamachrn

**Comment by cdrage** [comment]
@navidshaikh Eventually when this is all in OpenShift we could actually automatically update using ImageChange. But for now, it'd have to be done manually. Can you go ahead and do that to the prod environment @navidshaikh ? Pull / remove / re-add?

**Comment by bamachrn** [comment]
Done! @navidshaikh would you please recheck and close the issue?

**Comment by navidshaikh** [comment]
works!
