### ISSUE TITLE
Enforce migrations for database changes

### ISSUE THREAD

**Issue by mohammedzee1000** [CentOS/container-pipeline-service#554]
Moving forward, we need to start enforcing migrations for any changes to database. But what this also means is that the provisioning system will need to be faster and reproducible.

**Comment by bamachrn** [comment]
we are not using DB till now in the openshift cluster based architecture. Need to plan this properly when DB will be mandatory.

**Comment by dharmit** [comment]
Rather let's not start using DB without first being sure about performing migrations. :)
Also, avoid using it as long as possible. :)
