### ISSUE TITLE
Use registry catalog to find image list for weekly scan

### ISSUE THREAD

**Issue by dharmit** [CentOS/container-pipeline-service#559]
Earlier, we used to go through the container-index and registry catalog to verify which images on the container-index exist on the registry catalog and then push them for weekly scan.

Now, we're just going through the container-index: https://github.com/CentOS/container-pipeline-service/blob/b23d106599ecab861ef7a85d5dadeef1d93fdf0b/jenkinsbuilder/weekly-scan.py#L56-L71

As a result of our current approach, we're trying to scan images that don't exist on the registry.

Either we should go back to how we were doing things earlier or just check the registry catalog when trying to perform a weekly scan.

**Comment by bamachrn** [comment]
Re-structed from scratch in the new arch. PR: https://github.com/CentOS/container-pipeline-service/pull/615
