### ISSUE TITLE
Use devicemapper storage option as overlay2 doesn't support writable mounts (needed by pipeline-scanner)

### ISSUE THREAD

**Issue by navidshaikh** [CentOS/container-pipeline-service#567]
Current/broken atomic RPM version:   `atomic-1.22.1-1.gitd36c015.el7.centos.x86_64`
Working atomic RPM version:              `atomic-1.20.1-9.git436cf5d.el7.centos.x86_64`

Broken functionality:
```
atomic mount -o rw $IMAGE $MOUNT_POINT
```

Issue:
- Earlier atomic mount command as mentioned above will mount the image under test in read write mode allowing pipeline scanners to create lock files in the mounted filesystem when it calls `yum` command.

- Now, after mounting the image under test, and running pipeline scanner, the filesystem is mounted in read only mode, not allowing `yum` to create lock file.

**Comment by dharmit** [comment]
What's the error when we try to do `atomic mount -o rw`?

**Comment by navidshaikh** [comment]
@dharmit: I mentioned it in the issue, quoting again for your reference!
```
Now, after mounting the image under test, and running pipeline scanner, the filesystem is mounted in read only mode, not allowing yum to create lock fil
```

**Comment by navidshaikh** [comment]
To clarify further, this is complained by pipeline-scanner
```
"Error occured while processing yum updates. Cannot open logfile /scanin/_e60c69716e424d7bd4bad0bf2c9aa82eb98ed860db418846db2c1c32741f9f8c/var/log/yum.log\novl: Error while doing RPMdb copy-up:\n[Errno 30] Read-only file system: '/scanin/_e60c69716e424d7bd4bad0bf2c9aa82eb98ed860db418846db2c1c32741f9f8c/var/lib/rpm/.dbenv.lock'\nCould not create lock at /scanin/_e60c69716e424d7bd4bad0bf2c9aa82eb98ed860db418846db2c1c32741f9f8c/var/run/yum.pid: [Errno 30] Read-only file system: '/scanin/_e60c69716e424d7bd4bad0bf2c9aa82eb98ed860db418846db2c1c32741f9f8c/var/run/yum.pid' \n\n\nCan't create lock file; exiting\n", 
        "UUID": "e60c69716e424d7bd4bad0bf2c9aa82eb98ed860db418846db2c1c32741f9f8c"
```

**Comment by dharmit** [comment]
```bash
# atomic mount -o rw registry.centos.org/centos/centos:latest /mnt
The OverlayFS backend does not support writeable mounts.
# ls /mnt
# mkdir /somedir
# atomic mount -o rw registry.centos.org/centos/centos:latest /somedir
The OverlayFS backend does not support writeable mounts.
# atomic --version
1.20.1
```
It's not working even with the older version of atomic.

**Comment by navidshaikh** [comment]
> It's not working even with the older version of atomic.

The newer version will exit with exit status 0, and will mount the image in read-only mode (as opposed to requested read-write mode). While the subsequent operation (scanning by pipeline-scanner) expects the filesystem to be read-write mode, and fail. So there is a false positive. 

The older version will exit with exit status 1 and won't mount the image at all. Meaning, the mount operation will fail and it will prevent the pipeline-scanner invocation itself as the mount point is empty.

**Comment by navidshaikh** [comment]
We need to note  atomic mount in read write mode (which is needed by pipeline scanner) is not supported by `OverlayFS backend`.

On devcloud, atomic mount is complaining the backend is OverlayFS.

On pre-prod and prod, the backend is not OverlayFS, so even newer version of atomic can work on both environments.

**Comment by navidshaikh** [comment]
We are using `devicemapper` on pre-prod and prod environments, which is supported for writable mounts (and thus by atomic mount -o rw). We need to update docker-storage setup for non pre-prod and prod environments to have devicemapper as storage option.
