### ISSUE TITLE
Reg not loading Dockerfile / Description

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#578]
Looks like extra security has been enabled and three javascript libraries aren't loading (popper, jquery and bootstrap)

**Comment by cdrage** [comment]
@bamachrn fixed here: https://github.com/cdrage/reg/commit/3234ac40d317b5e154f74b6aa3d54e38c6c2f84d

**Comment by bamachrn** [comment]
closing this.
