### ISSUE TITLE
dotnet-21-centos7 image is not built using latest base

### ISSUE THREAD

**Issue by tmds** [CentOS/container-pipeline-service#609]
The `dotnet-21-centos7` image is not built upon its latest base image.
This causes s2i builds to fail because they depend on a file (`/opt/app-root/etc/trust_ssl_dirs`) from the base image (`dotnet/dotnet-21-runtime-centos7:latest`) which is missing.

https://github.com/CentOS/container-index/blob/master/index.d/dotnet.yaml has:

```
  - id: 5
    app-id: dotnet
    job-id: dotnet-21-centos7
...
    depends-on:
       - centos/centos:latest
       - dotnet/dotnet-21-runtime-centos7:latest
```

The file is present in the base image:
```
$ docker run  registry.centos.org/dotnet/dotnet-21-runtime-centos7 stat /opt/app-root/etc/trust_ssl_dirs
  File: '/opt/app-root/etc/trust_ssl_dirs'
  Size: 1772      	Blocks: 8          IO Block: 4096   regular file
Device: 30h/48d	Inode: 933821      Links: 1
Access: (0666/-rw-rw-rw-)  Uid: ( 1001/ default)   Gid: (    0/    root)
Access: 2018-08-28 05:26:23.000000000 +0000
Modify: 2018-08-28 05:26:23.000000000 +0000
Change: 2018-09-04 07:04:51.141285677 +0000
 Birth: -
```
But not in the dotnet-21-centos7 image:
```
$ docker run  registry.centos.org/dotnet/dotnet-21-centos7 stat /opt/app-root/etc/trust_ssl_dirs
stat: cannot stat '/opt/app-root/etc/trust_ssl_dirs': No such file or directory
```

The images were last built 7 days ago:
```
$ docker images -a
REPOSITORY                                             TAG                 IMAGE ID            CREATED             SIZE
registry.centos.org/dotnet/dotnet-21-centos7           latest              ed33f9659e75        7 days ago          569MB
registry.centos.org/dotnet/dotnet-21-runtime-centos7   latest              33d00b38a344        7 days ago          376MB
```

dotnet-21-centos7 Dockerfile: https://github.com/redhat-developer/s2i-dotnetcore/blob/master/2.1/build/Dockerfile
dotnet-21-runtime-centos7 Dockerfile: https://github.com/redhat-developer/s2i-dotnetcore/blob/master/2.1/runtime/Dockerfile

cc @aslicerh

**Comment by bamachrn** [comment]
@tmds this was brought up on 28-Aug-2018 and we checked on it. Also got confirmation there was no diff in containers manually built and the images in registry.centos.org. I am sure `dotnet-21-centos7` was built on `dotnet-21-runtime-centos7`. 

could you please look into [dotnet dockerfile](https://github.com/redhat-developer/s2i-dotnetcore/blob/master/2.1/build/Dockerfile) to check if it not changing something, which is causing this?

We are also verifying things again and will report back. please let us know if you find something.

**Comment by tmds** [comment]
When I build the s2i-dotnetcore repo locally for CentOS, the trust_ssl_dirs file is present in the dotnet/dotnet-21-centos7 image.

```sh
$ git clone https://github.com/redhat-developer/s2i-dotnetcore.git
...
$ BUILD_CENTOS=true VERSIONS=2.1 ./build.sh
...
$ docker run dotnet/dotnet-21-centos7 stat /opt/app-root/etc/trust_ssl_dirs
  File: '/opt/app-root/etc/trust_ssl_dirs'
  Size: 1772      	Blocks: 8          IO Block: 4096   regular file
Device: 54h/84d	Inode: 801316      Links: 1
Access: (0666/-rw-rw-rw-)  Uid: ( 1001/ default)   Gid: (    0/    root)
Access: 2018-08-28 12:47:06.000000000 +0000
Modify: 2018-08-28 12:47:06.000000000 +0000
Change: 2018-09-04 08:11:24.637860160 +0000
 Birth: -
```

Maybe something is wrong with the way the dotnet-21-centos7 image refers to the runtime image, causing it to pick up the wrong image.
```
FROM dotnet/dotnet-21-runtime-centos7
```

**Comment by bamachrn** [comment]
We triggered a build for `dotnet/dotnet-21-runtime-centos7`, which in turn triggered a build for `dotnet/dotnet-21-centos7`. Also checked the files are present as expected. Please validate once and let us know if there is still any difference. 

Also we are investigating on detail, why there was a difference in the images.

**Comment by tmds** [comment]
Thank you @bamachrn ! The files are indeed present with the latest images.

You can close this issue unless you want to use it for further tracking.

**Comment by bamachrn** [comment]
thanks! I will close the issue.
