### ISSUE TITLE
Error while overriding --entrypoint while running build, test, delivery_script

### ISSUE THREAD

**Issue by bamachrn** [CentOS/container-pipeline-service#64]
- For few containers, it is not allowing to override --entrypoint for running build_script. Whenever the container is started it starts docker starts some process (other than entrypoint) from container itself. As a result build goes in hold and fails to proceed to test stage. 
- Same thing happens for test_script and delivery_script for these containers.

**Comment by navidshaikh** [comment]
@bamachrn : is this still relevant ?
