### ISSUE TITLE
Fields of job information sent over tube

### ISSUE THREAD

**Issue by navidshaikh** [CentOS/container-pipeline-service#66]
We parse the the YAML file and prepares the data structure to be sent over beanstalk tube.
Here: https://github.com/CentOS/container-pipeline-service/blob/master/client/send_build_request.py#L9-L12
Excerpts:
```
build_details['name'] = sys.argv[1]
build_details['tag']  = sys.argv[2]
build_details['depends_on'] = sys.argv[3]
build_details['action'] = "start_build"
```

Then later, as per the worker / task to be done on job, we add / update the fields of information (fields of `build_details`).

This way, the information / fields of job information is altered / updated at different stages.

IMO, we should populate the job information with all the info provided via YAML file at once and then send across the tube.
This will make sure:
 - Every worker will have one source of referencing the information and consuming them
 - Other part of the code / worker need not to add the details in the job information which are needed for next phase
 - If there is additional information that needs to be added in `N` phase of flow and needed in `N+1` , `N` and `N+1` can handshake that before implementation.

**Comment by navidshaikh** [comment]
For example: We do not add user email address at first place when we are populating the data structure to be sent over the tube for build_phase, but we add it later when we want to trigger notify_user job. Now notify user worker is depending on the code which adds such information, however this information could have been part of `build_details` at the first place when we parsed the YAML file.

**Comment by dharmit** [comment]
I see an upside to this, sure. This would help in syncing various workers in the terms of data being consumed and generated and might be a good to have. However, I'm not sure how much value it adds at the moment since we're moving fast and, of course, breaking certain things while trying to add features or fix something. If the data being passed across different workers is causing an issue, this needs to be prioritized and worked upon sooner rather than later.

WDYT @bamachrn @kbsingh @rtnpro @mohammedzee1000 ?

**Comment by mohammedzee1000** [comment]
Yea definitely makes sense. It will require some refactor so im not sure we do it now or do it in the near future.

**Comment by kbsingh** [comment]
+1, sure - lets put the entire metadata we have for the specific job on the queue at one go. if nothing else it simplifies the work process, and does not need to reference the original data source file anymore. i.e once the job is started, it should keep going even when the orignating data stock changes ( and will be reflected in a subsequent job ).
