### ISSUE TITLE
Running /opt/cccp-service/client/build-project.sh does not update env vars for already existing project and it's builds

### ISSUE THREAD

**Issue by rtnpro** [CentOS/container-pipeline-service#68]
### Steps to reproduce
- Run `/opt/cccp-service/client/build-project.sh` for a project
- Update env vars, say, `TARGET_REPOSITORY` in `/opt/cccp-service/client/template.json`
- Run `/opt/cccp-service/client/build-project.sh` for the project again
- Check env variables for build for that project to see that they have not been updated
### Workaround

Run build script after deleting project on openshift, and you'll see the env vars updated.

**Comment by navidshaikh** [comment]
@range : What is use case here ?

**Comment by navidshaikh** [comment]
Closing the irrelevant issue.
