### ISSUE TITLE
Which container image repository is the supported one for pulling centos7 image?

### ISSUE THREAD

**Issue by zmiklank** [CentOS/container-pipeline-service#694]
Hello,

I am unable to find some official information about the supported centos7 container image.
It seems like `registry.centos.org` stopped working and the image on `quay.io/centos` is 3 years old.
From where should I pull centos7 image please?

Also, if this is not right place to ask could you please redirect me?

**Comment by bamachrn** [comment]
Hi @zmiklank please use the links from  https://www.centos.org/download/ , respectively https://hub.docker.com/_/centos and https://quay.io/repository/centos/centos

**Comment by phracek** [comment]
@bamachrn As @zmiklank wrote the image in repository https://quay.io/repository/centos/centos:centos7 is 3 years old.
Currently we use image from registry as `FROM registry.centos.org/centos/centos:7`
but if failed with reason:

```bash
Get https://registry.centos.org/v1/_ping: dial tcp: lookup registry.centos.org on 172.31.0.2:53: no such host
Pulling image registry.centos.org/centos/centos:7 failed.
Let's wait 5 seconds and try again.
Get https://registry.centos.org/v1/_ping: dial tcp: lookup registry.centos.org on 172.31.0.2:53: no such host
Pulling image regis
```

**Comment by zmiklank** [comment]
Hello @bamachrn, thank you for your answer.
Are the images on dockerhub and quay.io the same? It seems that the one from dockerhub is 6 months old, on quay.io 3 years old.

**Comment by phracek** [comment]
@bamachrn The registry https://registry.centos.org/ is not available, nor by `podman`

```bash
podman pull registry.centos.org/centos/centos:7
Trying to pull registry.centos.org/centos/centos:7...
Error: initializing source docker://registry.centos.org/centos/centos:7: pinging container registry registry.centos.org: Get "https://registry.centos.org/v2/": dial tcp: lookup registry.centos.org: no such host
```

**Comment by bamachrn** [comment]
@zmiklank I am not sure about that, but I would suggest to use the dockerhub one as it is updated.

**Comment by zmiklank** [comment]
@bamachrn and would it be possible to have updated also the image on quay.io?

**Comment by bamachrn** [comment]
Hi @phracek unfortunately, registry.centos.org is now decommissioned. As announced here https://lists.centos.org/pipermail/centos-devel/2023-May/142956.html

**Comment by bamachrn** [comment]
> @bamachrn and would it be possible to have updated also the image on quay.io?

@zmiklank I am not sure about this.

**Comment by zmiklank** [comment]
@bamachrn Thanks for your reply. Could you please then tell we where elsewhere can I ask about this?

**Comment by zmiklank** [comment]
I am closing this issue, as we got all the information we currently need. Thank you.
