### ISSUE TITLE
Image not tagged correctly there is more than one value in depends-on list. 

### ISSUE THREAD

**Issue by mohammedzee1000** [CentOS/container-pipeline-service#70]
I just noticed that images having more than one item in the depends on list are not getting tagged correctly.

For example consider https://github.com/CentOS/container-index/blob/master/index.d/openshift.yml#L140 which is for openshift/origin-deployer image. Its depends on contains two items, openshift/origin-base and openshift/origin. After the build, the same image gets tagged as openshift/origin-deployer:openshift/origin. 

Its not only this but all such images seem to be using the last value in the list as the tag instead of desired-tag.

**Comment by bamachrn** [comment]
This is because the shell script build-project.sh is not taking list as command line parameter. Need to implement this on a different way. We need to process depends on first for making build sequence and remove it from build-project parameter.

**Comment by navidshaikh** [comment]
@bamachrn : are you going to take this?

**Comment by bamachrn** [comment]
@navidshaikh yes, I am currently working on this.

**Comment by dharmit** [comment]
@bamachrn I think this one is waiting on the `depends-on` discussion we were having on the list, right?

**Comment by bamachrn** [comment]
@dharmit this is solved. we can close this. https://github.com/CentOS/container-pipeline-service/pull/97

**Comment by bamachrn** [comment]
@dharmit this is solved. we can close this. https://github.com/CentOS/container-pipeline-service/pull/97
