### ISSUE TITLE
Reserve duffy nodes for debugging on CI job failure

### ISSUE THREAD

**Issue by rtnpro** [CentOS/container-pipeline-service#78]
### Issue

Currently, we clean up the duffy nodes on ci.centos.org on CI job success/failure. It's fine when the jobs are successful, but on job failure, we should be able to login into the duffy nodes and debug things.
### Solution

On job failure, hit duffy's fail API endpoint, and print the hostnames of the nodes in the console output. This will automatically reserve the duffy nodes for 6 hours for debugging.

**Comment by dharmit** [comment]
@rtnpro I think you resolved this through #79, right? Can you please close the issue if it's taken care of?

**Comment by navidshaikh** [comment]
@rtnpro : should we close this ?

**Comment by navidshaikh** [comment]
This is in place now.
