### ISSUE TITLE
node.kubeconfig gets corrupted while simultanuos access by build and delivery worker

### ISSUE THREAD

**Issue by bamachrn** [CentOS/container-pipeline-service#80]
For login into openshift from worker we use ca.crt and node.kubeconfig from local file system. Whenever there is simultaneous access for node.kubeconfig from build and delivery worker, these files gets corrupted.
 As a reason for this we found oc client reads and writes node.kubeconfig in each login to openshift. 
To solve this we need to isolate the workers from each other giving them there own env each.

**Comment by navidshaikh** [comment]
@bamachrn : is this relevant anymore ?

**Comment by navidshaikh** [comment]
Fixed.
