### ISSUE TITLE
Non DRY workers

### ISSUE THREAD

**Issue by rtnpro** [CentOS/container-pipeline-service#86]
Currently, there's a lot of code repetition in the worker scripts and they are kind of always **REPEAT YOURSELF**. This makes it difficult to make changes without duplication of work. Currently, it seems that the project uses Python just as a scripting language, as a bash replacement, rather than a programming language. This needs to be fixed.

Just my 2 cents.

**Comment by bamachrn** [comment]
@rtnpro please keep in mind, the workers should be running totally independent on each other. We may need to scale build worker, that should not impact other workers even though they are not scaled.

**Comment by rtnpro** [comment]
On Fri, Oct 7, 2016 at 2:10 PM, Bamacharan Kundu
<notifications@github.com> wrote:
>
> @rtnpro please keep in mind, the workers should be running totally independent on each other.
That's not a good enough reason to have the same code in multiple
files. We can have a lib with the common helper functions and reuse
that in the worker scripts/modules.

> We may need to scale build worker, that should not impact other workers even though they are not scaled.

I don't see how it's related to writing DRY code.

**Comment by kbsingh** [comment]
@rtnpro can you raise a card for this work, and make sure it hits the planning sessions and everyone has buyin as to the urgency and scope of the work before spending any time on this.

**Comment by navidshaikh** [comment]
This is fixed with worker refactoring.
