### ISSUE TITLE
Index test validations for mandatory and optional fields for input job config

### ISSUE THREAD

**Issue by navidshaikh** [CentOS/container-pipeline-service#88]
Index test validations check for fields provided per job config, there are checks for presence of fields for particular job, the assurance needs to be modified to not error on optional fields, eg: `desired-tag` .

https://github.com/CentOS/container-pipeline-service/blob/master/testindex/Validators.py#L100

**Comment by navidshaikh** [comment]
@mohammedzee1000  ping

**Comment by mohammedzee1000** [comment]
@navidshaikh we initially thought the same. But @kbsingh said that the fields in index must be present, for example desired-tag is latest if nothing is provided, but the value desired-tag: latest must be present in the index.

**Comment by navidshaikh** [comment]
This has become irrelevant. Closing the issue.
