### ISSUE TITLE
Failed builds notification emails are not sent

### ISSUE THREAD

**Issue by navidshaikh** [CentOS/container-pipeline-service#89]
The service is not sending the notifications for failed builds.

**Comment by navidshaikh** [comment]
The code is commented out  https://github.com/CentOS/container-pipeline-service/blob/master/server/run.sh#L83

**Comment by navidshaikh** [comment]
@bamachrn : ping

**Comment by bamachrn** [comment]
this has been taken care of in https://github.com/CentOS/container-pipeline-service/pull/84
